### ISSUE TITLE
Bessere Kopfhörer/Mikrofone 

### ISSUE THREAD

**Issue by tschaka1904** [codestammtisch/general#1]

**Comment by zeitschlag** [comment]
Im Sendegate gibt es eine ganze Kategorie zum Thema Hardware. Da wird u.a. auf [dieses Setup](https://sendegate.de/t/profi-klang-fuer-alle-das-hmc660-headset-richtig-einsetzen-fuer-unter-100/3076) verwiesen. Pro Nase wären das 100€.

Wie gehen wir mit Gästen um? Müssen die einfach ein eigenes Mikrofon haben?

**Comment by tschaka1904** [comment]
Ich bin in vielen Reviews über das [H390 USB COMPUTER HEADSET](https://www.logitech.com/en-us/product/stereo-headset-h390) gestolpert. Es kostet etwa 30€ und soll eine gute Qualität haben. Es wäre ein günstiger Einstieg und wir könnten später immer noch upgraden.

**Comment by tschaka1904** [comment]
Auch das Sennheiser [PC 8 USB Headset](https://de-ch.sennheiser.com/usb-pc-headset-stereo-pc-8-usb?gclid=CjwKCAjwwJrbBRAoEiwAGA1B_d4DbWt0oQp9rVLi4XLD2FpOlmRkbN0eGmjMebJPcOYlArrj0dRdqxoCrHsQAvD_BwE) scheint gut zu sein. Ähnliche Preisklasse. 

Quelle: https://www.thepodcasthost.com/equipment/headset-microphones-for-podcasting/

**Comment by zeitschlag** [comment]
Wow, ich muss sagen, der Klang vom PC 8 überrascht mich positiv :-) Es überzeugt mich mehr als das [H390](https://www.youtube.com/watch?v=hTWVmLbQBSg) tbh.

Wollen wir dann erstmal mit 2 PC 8 starten? Oder 1 PC 8 und 1 H390?

**Comment by zeitschlag** [comment]
Max und ich haben uns jeweils ein H390 gekauft. Bei der letzten Aufnahme gab es allerdings irgendwelche Interferenzen zwischen Charger und USB-Soundkarte gab. Workaround: Laptop das nächste Mal ganz aufladen? Anderen USB-Anschluss nutzen? Irgendwo erden?

**Comment by zeitschlag** [comment]
Ich mache diesen Issue nochmal auf, weil beide Headsets ein hörbares Brummen erzeugen

**Comment by tschaka1904** [comment]
Ich habe mir mal das Trust EMITA zugelegt. Hier gibts ne review von nem anderen Podcaster: https://www.rosenblut.org/2018/03/07/trust-gxt-252-emita-streaming-mikrofon/

**Comment by zeitschlag** [comment]
Hat sich erledigt, schliesse ich mal
